version: '3'
services:
  dbpostgres:
    image: postgres
    volumes:
      - questiondb-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: questiondb

volumes:
  questiondb-data: